# config_version=4

images:
  double_scoring_active:
    file: 2x_scoring_active.png
  dead_flip_center:
    file: dead_flip_center.png
  dead_flip_fill:
    file: dead_flip_fill.png
  eagle_one:
    file: eagleone.png
  fast_logo:
    file: fast_logo.png
  mpf_logo:
    file: mpf_logo.png
  sb_logo_1:
    file: spaceballs_logo_1.png
  goneplaid_frame1:
    file: plaid_frame1.png
  goneplaid_frame2:
    file: plaid_frame2.png
  goneplaid_frame3:
    file: plaid_frame3.png
  goneplaid_frame4:
    file: plaid_frame4.png
  goneplaid_frame5:
    file: plaid_frame5.png
  goneplaid_frame6:
    file: plaid_frame6.png
  goneplaid_frame7:
    file: plaid_frame7.png
  perriair_logo:
    file: perriair_logo.png
  planet_druidia:
    file: planetdruidia.png
  skillshot_instructions:
    file: skillshot_instructions.png
  splash_screen:
    file: spaceballs_spash_screen.jpg
  virgin_alarm:
    file: virgin_alarm.png
