# config_version=4

keyboard:
  z:
    switch: s_left_flipper
  /:
    switch: s_right_flipper
  1:
    switch: s_drop_1
    toggle: true
  2:
    switch: s_drop_2
    toggle: true
  3:
    switch: s_drop_3
    toggle: true
  4:
    switch: s_drop_4
    toggle: true
  5:
    switch: s_drop_5
    toggle: true
  p:
    switch: s_plunger_lane
    toggle: true
  l:
    switch: s_launch_button
  s:
    switch: s_start

