# config_version=4

switches:
#BEGIN 0804 (0-7)
  s_right_flipper:
    number: 0
    tags: right_flipper
  s_launch_button:
    number: 1
    tags: launch
  s_left_flipper:
    number: 2
    tags: left_flipper
  s_start:
    number: 3
    tags: start
#BEGIN 3208 (8-39)
  s_trough1:
    number: 8
    type: NC
  s_trough2:
    number: 9
    type: NC
  s_trough3:
    number: 10
    type: NC
  s_trough4:
    number: 11
    type: NC
  s_trough5:
    number: 12
    type: NC
  s_trough6:
    number: 13
    type: NC
  s_trough_jam:
    number: 14
    type: NC
  s_plunger_lane:
    number: 15
  s_saucer:
    number: 16
  s_scoop:
    number: 17
  s_drop_2:
    number: 18
  s_drop_1:
    number: 19
  s_drop_3:
    number: 20
  s_drop_5:
    number: 21
  s_drop_4:
    number: 22
  s_sbone_left_orbit:
    number: 23
  s_sling_right:
    number: 24
  s_sling_left:
    number: 25
  s_left_inlane:
    number: 26
  s_left_outlane:
    number: 27
  s_right_inlane:
    number: 28
  s_right_outlane:
    number: 29
  s_sbone_right_orbit:
    number: 30
  s_pop_sneak:
    number: 31
  s_sbone_lock_3:
    number: 32
    type: NC
  s_sbone_lock_2:
    number: 33
    type: NC
  s_sbone_lock_1:
    number: 34
    type: NC
  s_ramp_entry:
    number: 35
    type: NC
  s_sbone_entry:
    number: 36
    type: NC
  s_ramp_exit:
    number: 37
    type: NC
  s_right_orbit:
    number: 38
    type: NC
#BEGIN 1616 (40-55)
  s_pop_1:
    number: 40
    tags: pop_hit
  s_pop_2:
    number: 41
    tags: pop_hit
  s_pop_3:
    number: 42
    tags: pop_hit
  s_air_a_lane:
    number: 43
  s_air_i_lane:
    number: 44
  s_air_r_lane:
    number: 45
  s_left_spinner:
    number: 46
    debounce_open: 2
    debounce_close: 2
  s_schwartz_power_1:
    number: 48
  s_schwartz_power_2:
    number: 49
  s_schwartz_power_3:
    number: 50
  s_schwartz_power_4:
    number: 51
  s_schwartz_power_5:
    number: 52
  s_schwartz_power_6:
    number: 53
  s_schwartz_power_7:
    number: 54
  s_middle_target:
    number: 55
