#config_version=4

assets:
  videos:
    default:
      load: preload

videos:
  introcrawl:
    file: IntroCrawl.mp4
  introship:
    file: IntroShip.mp4
  airlock_king_one:
    file: Airlock_Combination_1_King.mp4
  airlock_king_two:
    file: Airlock_Combination_2_King.mp4
  airlock_king_three:
    file: Airlock_Combination_3_King.mp4
  airlock_king_four:
    file: Airlock_Combination_4_King.mp4
  airlock_king_five:
    file: Airlock_Combination_5_King.mp4
  allrise_for_darkhelmet:
    file: All_Rise_In_The_Presence_Of_Dark_Helmet.mp4
  barf_intro:
    file: Barf_Intro.mp4
  chestburster_end:
    file: Chestburster_End.mp4
  chestburster_start:
    file: Chestburster_Start.mp4
    events_when_stopped: chestburster_start_video_stopped
  darkhelmet_flying_forward:
    file: Dark_Helmet_Flying_Forward.mp4
  darkhelmet_lightspeed_flying:
    file: Dark_Helmet_Lightspeed_Flying.mp4
  gimme_paw:
    file: Gimme_Paw.mp4
  going_plaid_transition:
    file: Going_Plaid_Transition.mp4
  gunners_mate_phillip_asshole:
    file: Gunners_Mate_First_Class_Phillip_Asshole.mp4
  hail_skroob:
    file: Hail_Skroob.mp4
  hello_lonestar_1:
    file: Hello_Lonestar_1.mp4
  hello_lonestar_2:
    file: Hello_Lonestar_2.mp4
  here_it_is_spaceballs:
    file: Here_It_Is_Sir_Spaceballs.mp4
  hes_an_asshole_sir:
    file: Hes_An_Asshole_Sir.mp4
  hes_an_asshole_too:
    file: Hes_An_Asshole_Too_Sir.mp4
  how_many_assholes_we_got:
    file: How_Many_Assholes_We_Got_Anyhow.mp4
  my_own_best_friend:
    file: Im_My_Own_Best_Friend.mp4
  surrounded_by_assholes:
    file: Im_Surrounded_By_Assholes.mp4
  keep_firing_assholes:
    file: Keep_Firing_Assholes.mp4
  major_asshole:
    file: Major_Asshole.mp4
  make_way_for_darkhelmet:
    file: Make_Way_For_Dark_Helmet.mp4
  brains_in_my_feet:
    file: My_Brains_Are_Going_Into_My_Feet.mp4
  oh_shit:
    file: Oh_Shit.mp4
  pizza_the_hut_intro:
    file: Pizza_The_Hut_Intro.mp4
  skroob_scratching_crotch:
    file: Skroob_Scratching_Crotch.mp4
  skroob_shithead:
    file: Skroob_Shithead.mp4
  start_lightspeed:
    file: Start_Light_Speed.mp4
  theyve_gone_to_plaid:
    file: Theyve_Gone_To_Plaid.mp4